version: "3.9"
services:
  dev:
    image: node:18
    container_name: dev-instance
    working_dir: /app
    volumes:
      - ./dev-app:/app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm cache clean --force && npm install --unsafe-perm && npm run dev"

  tests:
    image: python:3.11
    container_name: test-instance
    working_dir: /tests
    volumes:
      - ./test-app:/tests
    depends_on:
      - dev
    environment:
      BASE_URL: "http://dev:5173/"
      LOG_DIR: "logs/logs_data"
      SCREENSHOT_DIR: "utils/screenshots"
      LOG_COLLECTOR_HOST: "dev"
      LOG_COLLECTOR_PORT: 9020
    command: >
      sh -c "pip install -r requirements.txt && pytest"
